apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: urturn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urturn
  template:
    metadata:
      labels:
        app: urturn  
    spec:                  
      containers: 
      - name: urturn-app
        image: gcr.io/urturn-1/urturn-image:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_PORT
          value: "3000"
        - name: MONGODB_DBNAME
          value: prod
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /opt/firebase-admin-sdk-creds
        - name: FIREBASE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: firebase-prod-url
              key: firebase-prod-url
        - name: MONGODB_CONNECT_STRING
          valueFrom:
            secretKeyRef:
              name: mongo-prod-url
              key: mongo-prod-url
        volumeMounts:
          - name: firebase-admin-sdk-creds
            mountPath: "/opt/firebase-admin-sdk-creds"
            readOnly: true
      volumes:
      - name: firebase-admin-sdk-creds
        secret:
            secretName: firebase-admin-sdk-creds-json
