apiVersion: v1
kind: Service
metadata:
  name: urturn-nodeport
  labels:
    app: urturn
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"urturn-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: urturn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
